-- Dev convenience: auto-create the users table on first PostgreSQL init
-- (runs via /docker-entrypoint-initdb.d). For real environments use the
-- mybatis-schema-migration module instead.
CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    created_by BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    del_flag SMALLINT NOT NULL DEFAULT 0
);
